### ISSUE TITLE
Scatterer - JNSQ / CKAN minor issue

### ISSUE THREAD

**Issue by Jognt** [Galileo88/JNSQ#26]
JNSQ has "Scatterer - Default Config" set as a dependency in CKAN while it actually provides a cfg itself.
This leads to Scatterer reporting double installations of Scatterer because CKAN does not allow installing only Scatterer core and auto-installs the default cfg.

**Comment by DasSkelett** [comment]
> JNSQ has "Scatterer - Default Config" set as a dependency in CKAN

Are you sure? Doesn't look like it in the [netkan](https://github.com/Galileo88/JNSQ/blob/master/CKAN/JNSQ.netkan) file:
```
  "depends": [
    {
      "name": "ModuleManager"
    },
    {
      "name": "Kopernicus"
    }
  ],
```

> while it actually provides a cfg itself.

Also can't confirm that, the included config files seem to depend on the default config files from Scatterer, if I understand the MM syntax correctly: https://github.com/Galileo88/JNSQ/blob/master/GameData/JNSQ/JNSQ_Configs/Scatterer/config.cfg

**Comment by Jognt** [comment]
The ‘double instance’ from Scatterer appears to be caused internally with Scatterer itself. Please disregard. 

With regards to CKAN/MM, that looks much different from what I saw when I checked. May have checked an older release where MM syntax was much less consistent. 

I will double check and report back. Please stand by.

**Comment by Jognt** [comment]
Not sure what I was doing. I was probably drawing premature conclusion based on an issue over at scatterer's github.

While checking I did see the reason why I had no sunflare in scatterer mode:
JNSQ Netkan: "Provides scatterer sunflare"
JNSQ Sunflare: "@scatterer_sunflare"

Removing the @ should be enough:
https://github.com/Galileo88/JNSQ/blob/master/GameData/JNSQ/JNSQ_Configs/Scatterer/sunflare01.cfg

**Comment by DasSkelett** [comment]
> While checking I did see the reason why I had no sunflare in scatterer mode:
> JNSQ Netkan: "Provides scatterer sunflare"
> JNSQ Sunflare: "@scatterer_sunflare"

Yes indeed, good catch. We had this problem with multiple planet packs now.
It looks like they would provide the entire sunflare config themselves, but they actually only modify the default ones, just like the `Scatterer-config`. Tricky ModuleManager syntax.


> Removing the @ should be enough:
> [/GameData/JNSQ/JNSQ_Configs/Scatterer/sunflare01.cfg@`master`](https://github.com/Galileo88/JNSQ/blob/master/GameData/JNSQ/JNSQ_Configs/Scatterer/sunflare01.cfg) [](/Galileo88/JNSQ/blob/HEAD@{2020-05-06T02:34:20Z}/GameData/JNSQ/JNSQ_Configs/Scatterer/sunflare01.cfg)

This has to be solved in the CKAN metadata, the `"provides": "Scatterer-sunflare"` should be changed to a `"depends": "Scatterer-sunflare"`
If the JNSQ team decides to provide the full sunflare config in the future, it will have to be changed it back.

I'm going to do a PR here to update the NetKAN file (since it's hosted in this repo), and then we also have to backport the change to earlier releases in the CKAN-meta repository.

**Comment by Jognt** [comment]
Cheers. Shall I close this or keep it open?

**Comment by DasSkelett** [comment]
Keep it open, I'm going to close it with the PR.
